# Site settings
title: STOOP Charity walk, May 2024
tag_text: Brain Tumour Charity
description: Walking the STOOP for The Brain Tumour Charity on May 25th and 26th

# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://stoop.org.uk" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
